import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://www.amazon.fr/');
  await page.getByRole('button', { name: 'Accepter' }).click();
  await page.getByRole('searchbox', { name: 'Rechercher Amazon.fr' }).click();
  await page.getByRole('searchbox', { name: 'Rechercher Amazon.fr' }).click();
  await page.getByRole('searchbox', { name: 'Rechercher Amazon.fr' }).fill('basket');
  await page.getByRole('button', { name: 'Go', exact: true }).click();
  await page.getByRole('listitem').filter({ hasText: '+ 4 autres couleurs/motifsÀ' }).getByRole('link').first().click();
  await page.getByRole('button', { name: 'Ajouter au panier', exact: true }).click();
  await page.getByRole('button', { name: 'Passer la commande (1 article' }).click();
  await page.getByRole('textbox', { name: 'Adresse e-mail ou numéro de t' }).click();
  await page.getByRole('heading', { name: 'S\'identifier' }).click();
  await page.getByRole('link', { name: 'www.amazon.fr' }).click();
  await page.goto('https://www.amazon.fr/');
  await page.getByRole('button', { name: 'Accepter' }).click();
  await page.getByRole('searchbox', { name: 'Rechercher Amazon.fr' }).click();
  await page.getByRole('searchbox', { name: 'Rechercher Amazon.fr' }).click();
  await page.getByRole('searchbox', { name: 'Rechercher Amazon.fr' }).fill('basket');
  await page.getByRole('button', { name: 'Go', exact: true }).click();
  await page.getByRole('listitem').filter({ hasText: '+ 4 autres couleurs/motifsÀ' }).getByRole('link').first().click();
  await page.getByRole('button', { name: 'Ajouter au panier', exact: true }).click();
  await page.getByRole('button', { name: 'Passer la commande (1 article' }).click();
  await page.getByRole('textbox', { name: 'Adresse e-mail ou numéro de t' }).click();
  await page.getByRole('heading', { name: 'S\'identifier' }).click();
  await page.getByRole('link', { name: 'www.amazon.fr' }).click();
  await page.goto('https://www.amazon.fr/');
  await page.getByRole('button', { name: 'Accepter' }).click();
  await page.getByRole('searchbox', { name: 'Rechercher Amazon.fr' }).click();
  await page.getByRole('searchbox', { name: 'Rechercher Amazon.fr' }).click();
  await page.getByRole('searchbox', { name: 'Rechercher Amazon.fr' }).fill('basket');
  await page.getByRole('button', { name: 'Go', exact: true }).click();
  await page.getByRole('listitem').filter({ hasText: '+ 4 autres couleurs/motifsÀ' }).getByRole('link').first().click();
  await page.getByRole('button', { name: 'Ajouter au panier', exact: true }).click();
  await page.getByRole('button', { name: 'Passer la commande (1 article' }).click();
  await page.getByRole('textbox', { name: 'Adresse e-mail ou numéro de t' }).click();
  await page.getByRole('heading', { name: 'S\'identifier' }).click();
  await page.getByRole('link', { name: 'www.amazon.fr' }).click();
  await page.goto('https://www.amazon.fr/');
  await page.getByRole('button', { name: 'Accepter' }).click();
  await page.getByRole('searchbox', { name: 'Rechercher Amazon.fr' }).click();
  await page.getByRole('searchbox', { name: 'Rechercher Amazon.fr' }).click();
  await page.getByRole('searchbox', { name: 'Rechercher Amazon.fr' }).fill('basket');
  await page.getByRole('button', { name: 'Go', exact: true }).click();
  await page.getByRole('listitem').filter({ hasText: '+ 4 autres couleurs/motifsÀ' }).getByRole('link').first().click();
  await page.getByRole('button', { name: 'Ajouter au panier', exact: true }).click();
  await page.getByRole('button', { name: 'Passer la commande (1 article' }).click();
  await page.getByRole('textbox', { name: 'Adresse e-mail ou numéro de t' }).click();
  await page.getByRole('heading', { name: 'S\'identifier' }).click();
  await page.getByRole('link', { name: 'www.amazon.fr' }).click();
  await page.goto('https://www.amazon.fr/');
  await page.getByRole('button', { name: 'Accepter' }).click();
  await page.getByRole('searchbox', { name: 'Rechercher Amazon.fr' }).click();
  await page.getByRole('searchbox', { name: 'Rechercher Amazon.fr' }).click();
  await page.getByRole('searchbox', { name: 'Rechercher Amazon.fr' }).fill('basket');
  await page.getByRole('button', { name: 'Go', exact: true }).click();
  await page.getByRole('listitem').filter({ hasText: '+ 4 autres couleurs/motifsÀ' }).getByRole('link').first().click();
  await page.getByRole('button', { name: 'Ajouter au panier', exact: true }).click();
  await page.getByRole('button', { name: 'Passer la commande (1 article' }).click();
  await page.getByRole('textbox', { name: 'Adresse e-mail ou numéro de t' }).click();
  await page.getByRole('heading', { name: 'S\'identifier' }).click();
  await page.getByRole('link', { name: 'www.amazon.fr' }).click();
  await page.goto('https://www.amazon.fr/');
  await page.getByRole('button', { name: 'Accepter' }).click();
  await page.getByRole('searchbox', { name: 'Rechercher Amazon.fr' }).click();
  await page.getByRole('searchbox', { name: 'Rechercher Amazon.fr' }).click();
  await page.getByRole('searchbox', { name: 'Rechercher Amazon.fr' }).fill('basket');
  await page.getByRole('button', { name: 'Go', exact: true }).click();
  await page.getByRole('listitem').filter({ hasText: '+ 4 autres couleurs/motifsÀ' }).getByRole('link').first().click();
  await page.getByRole('button', { name: 'Ajouter au panier', exact: true }).click();
  await page.getByRole('button', { name: 'Passer la commande (1 article' }).click();
  await page.getByRole('textbox', { name: 'Adresse e-mail ou numéro de t' }).click();
  await page.getByRole('heading', { name: 'S\'identifier' }).click();
  await page.getByRole('link', { name: 'www.amazon.fr' }).click();
  // await page.getByRole('link', { name: 'www.amazon.fr' }).click();
});